functionsDirectory = "C:\\Users\\baral\\Downloads\\Team-Vortex\\movie-site\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\baral\\Downloads\\Team-Vortex\\movie-site"
publishOrigin = "config"
base = "C:\\Users\\baral\\Downloads\\Team-Vortex\\movie-site"
functions = "C:\\Users\\baral\\Downloads\\Team-Vortex\\movie-site\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/server"
to = "/server.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]